version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: prashanthsams/json-server
    machine: true
    steps:
      - checkout
      - run:
          name: build application docker image
          command: |
            docker build  -t json-server  .
      - run:
          name: Validating the test results
          command: |
            docker run -i json-server  > result
            sh -c "[ -s result ]"
  publish-latest:
    environment:
      IMAGE_NAME: prashanthsams/json-server
      USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    machine: true
    steps:
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
                  cat ${{ secrets.docker.DOCKERHUB_USERNAME }}
                  echo $PASSWORD | docker login -u $USERNAME --password-stdin
                  docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master