version: 2
jobs:
  build:
    working_directory: ~/app
    environment:
      IMAGE_NAME: prashanthsams/json-server
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout:
      - setup_remote_docker
      - run:
          name: build application docker image
          command: |
            docker build  -t json-server  .
      - run:
          name: Validating the test results
          command: |
            docker run -i json-server  > result
            sh -c "[ -s result ]"
  publish-latest:
    working_directory: ~/app
    environment:
      IMAGE_NAME: prashanthsams/json-server
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout:
      - setup_remote_docker
      - run:
          name: Publish Docker Image
          command: |
                  echo ${{ env.DOCKERHUB_PASSWORD }} | docker login --username ${{ env.DOCKERHUB_USERNAME }} --password-stdin
                  docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master